name: Link PR to Issue

on:
  pull_request:
    types: [opened, edited]
permissions:
  issues: write
jobs:
  link:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.40.x"
      - name: Update issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: deno run --allow-net --allow-env action.ts
        working-directory: .github/workflows/link-pr
