name: Link PR to Issue

on:
  pull_request:
    types: [ opened, edited ]
  workflow_dispatch:
    inputs: []
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v3
      - name: Update issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: node .github/workflows/link-pr/link-pr.js
