name: Link PR to Issue

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: .github
      - name: Update issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: node .github/workflows/link-pr/link-pr.js
