name: Link PR to Issue

on:
  pull_request:
    types: [ opened, edited, connected, disconnected ]
permissions:
  issues: write
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.7.0"
      - name: Update issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bun run .github/workflows/link-pr/action.ts
