name: Use reusable workflow

on:
  workflow_dispatch:
    inputs: {}
jobs:
  use-reusable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/natoc-zmrzlinu
